title: Constantinos Kyriacou # your name (or website title) here
logo: "/images/picture1.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Postgraduate student of Data Science at University of Essex Online <br><br>  
theme: jekyll-theme-minimal
google_analytics: CKyriacou1-307804336 # your Google Analytics tracking ID here
